clear; clc;

% ========================================================================
% Convert ERA5 NetCDF files to Delft3D meteorological forcing files
%
% This script:
%   1. Reads ERA5 hourly meteorological data from NetCDF files
%   2. Extracts:
%        - Mean Sea Level Pressure (msl)
%        - 10 m U-wind component (u10)
%        - 10 m V-wind component (v10)
%   3. Reformats the ERA5 grids
%   4. Creates yearly Delft3D wind files (*.amu and *.amv)
%
% NOTE:
% Atmospheric pressure (*.ampr) is not yet generated by the current
% WriteOwiDelft3D.m function.
%
% ========================================================================

%% -----------------------------------------------------------------------
% User settings
%% -----------------------------------------------------------------------

years = 2020:2020;      % Modify as desired

%% -----------------------------------------------------------------------
% Loop over years
%% -----------------------------------------------------------------------

for yr = years

    ncName = sprintf('era5_%d.nc',yr);

    fprintf('\n=========================================\n');
    fprintf('Processing %s\n',ncName);
    fprintf('=========================================\n');

    %% ------------------------------------------------------------------
    % Read time
    %% ------------------------------------------------------------------

    time = ncread(ncName,"valid_time");
    time = datenum(datetime(1970,1,1) + seconds(time));

    %% ------------------------------------------------------------------
    % Read coordinates
    %% ------------------------------------------------------------------

    lat = ncread(ncName,"latitude");
    lon = ncread(ncName,"longitude");

    %% ------------------------------------------------------------------
    % Read variables
    %% ------------------------------------------------------------------

    msl = ncread(ncName,"msl")*0.01;      % Pa → mb
    u10 = ncread(ncName,"u10");
    v10 = ncread(ncName,"v10");

    %% ------------------------------------------------------------------
    % Reorient ERA5 arrays
    %% ------------------------------------------------------------------

    msl = permute(msl,[2 1 3]);
    u10 = permute(u10,[2 1 3]);
    v10 = permute(v10,[2 1 3]);

    msl = flipud(msl);
    u10 = flipud(u10);
    v10 = flipud(v10);

    %% ------------------------------------------------------------------
    % Build OWI structure
    %% ------------------------------------------------------------------

    owi.Basin = [];

    owi.Basin.time = time';

    owi.Basin.iLat = length(lat)*ones(1,length(time));
    owi.Basin.iLong = length(lon)*ones(1,length(time));

    owi.Basin.DX = abs(lon(2)-lon(1))*ones(1,length(time));
    owi.Basin.DY = abs(lat(2)-lat(1))*ones(1,length(time));

    owi.Basin.SWLat = lat(end)*ones(1,length(time));
    owi.Basin.SWLon = lon(1)*ones(1,length(time));

    [owi.Basin.XGrid{1:length(time)}] = deal(lon');
    [owi.Basin.YGrid{1:length(time)}] = deal(flip(lat));

    %% ------------------------------------------------------------------
    % Store fields
    %% ------------------------------------------------------------------

    for k = 1:length(time)

        owi.Basin.Pre{k} = msl(:,:,k);

        owi.Basin.WinU{k} = u10(:,:,k);

        owi.Basin.WinV{k} = v10(:,:,k);

    end

    %% ------------------------------------------------------------------
    % No nested grid
    %% ------------------------------------------------------------------

    owi.Region = [];

    %% ------------------------------------------------------------------
    % Write Delft3D files
    %% ------------------------------------------------------------------

    outName = sprintf('era5_%d',yr);

    WriteOwiDelft3D(owi,outName);

    fprintf('Finished %d\n',yr);

    clear owi time lat lon msl u10 v10

end

fprintf('\n=========================================\n');
fprintf('All requested years completed.\n');
fprintf('=========================================\n');